#!/usr/bin/env sh

# Location of the .jar file
JAR="$(dirname $0)/target/hexmc-jar-with-dependencies.jar"

# This script relies on the JAR variable above, and therefore should not be placed in another directory.
# If you want to run the solver from other directories, create another script that runs this script.

if [ ! -f "$JAR" ]
then
    echo "The executable file does not exist. Run './build' to compile."
    exit 1
fi

java -jar "$JAR" "$@"
