#!/bin/bash

BASEDIR=$(dirname "$0")
JAR="${BASEDIR}/target/hexmc-jar-with-dependencies.jar"

if [ ! -f "$JAR" ]
then
    echo "The executable file does not exist. Run './build' to compile."
    exit 1
fi

java -jar "$JAR" "$@"
