name: Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and run tests
        run: |
          cd solver
          mvn --batch-mode clean install
      - name: Upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: target/surefire-reports/*.txt
